server {
    listen 8080;

    root /usr/share/nginx/html;
    index index.html;

    # Проксируем API-запросы на бэкенд
    location /api/ {
        proxy_pass http://backend:8081;
        proxy_set_header Host $host;
    }

    # Все остальные запросы отдаём index.html (для Vue Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
